### ISSUE TITLE
1.8.8 spigot

### ISSUE THREAD

**Issue by Szabolcs2008** [Dysaido/PvPEvent#1]
I'm getting this error whenever I'm trying to save:
I've tried to use older versions of the plugin, same issue...
Is there a dependency that i dont know of?

```
[14:28:57 INFO]: balazsqah issued server command: /events save
[14:28:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'events save' in xyz.dysaido.pvpevent.command.impl.EventsCommand(events)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362-362]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_362-362]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362-362]
Caused by: java.lang.NullPointerException
        at xyz.dysaido.pvpevent.util.LocationSerializer.serialize(LocationSerializer.java:13) ~[?:?]
        at xyz.dysaido.pvpevent.arena.ArenaManager.save(ArenaManager.java:52) ~[?:?]
        at xyz.dysaido.pvpevent.command.impl.EventsCommand.handle(EventsCommand.java:173) ~[?:?]
        at xyz.dysaido.pvpevent.command.BaseCommand.execute(BaseCommand.java:41) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
        ... 14 more
```

**Comment by Dysaido** [comment]
Hi, sorry that i haven't answered you. I updated this plugin so you can download this from spigotmc. I knew this plugin has a lot of problem and because of this i tried to recode

**Comment by Dysaido** [comment]
Fixed
